---
- hosts: all
  become: yes  
  tasks: 
     - name: install java in ubuntu
       apt: 
            name: "{{ java_ubuntu }}"
            state: present
       when: ansible_os_family == "Debian"    

     - name: install webserver in rhel 
       yum: 
          name: "{{ java_rhel }}"
          state: present       
       when: ansible_os_family == "RedHat"
