---
- hosts: all
  become: true 
  tasks:
     - name: install package in ubuntu
       apt:
            name: "{{ item }}" 
            state: present
            update_cache: yes
       with_items:
           - git
           - wget
           - tree